# Generated by Django 3.1.7 on 2021-05-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person_post_userslikedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.CharField(max_length=512),
        ),
    ]
