# Generated by Django 3.1.7 on 2021-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210511_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(height_field=370, upload_to='', width_field=370),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(height_field=370, upload_to='', width_field=370),
        ),
    ]
